# Generated by Django 3.1.2 on 2020-11-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201107_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maxunits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
