# Generated by Django 3.1.2 on 2020-11-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201108_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ['register_date'], 'permissions': (('can_mark_available', 'Set products as available'),)},
        ),
    ]
